### ISSUE TITLE
Add content from NLP email

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/low-resource-languages#148]
I've gotten these links off of the SIGUL list, from Sebastien Ruder's email list:

- https://www.indobenchmark.com/?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter
- https://github.com/neubig/lowresource-nlp-bootcamp-2020?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter
- https://stanfordnlp.github.io/stanza/?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter
- https://www.masakhane.io/?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter
- https://github.com/ARBML/ARBML?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter
- https://github.com/ahmetaa/zemberek-nlp?utm_campaign=NLP%20News&utm_medium=email&utm_source=Revue%20newsletter

These would be great to add.

**Comment by TheMightyKegel** [comment]
Race & Ethnicity Coding Guidelines may impact implementation or review process within and outside program language development.

Reference link: https://iaphs.org/beyond-the-boxes-part-4-complications-in-coding-race-and-ethnicity/
