### ISSUE TITLE
Race & Ethnicity Coding Guidelines may impact implementation or review process within and outside program language development

### ISSUE THREAD

**Issue by TheMightyKegel** [RichardLitt/low-resource-languages#155]
Reference link: https://iaphs.org/beyond-the-boxes-part-4-complications-in-coding-race-and-ethnicity/

**Comment by RichardLitt** [comment]
Thanks. This doesn't look like an open source coding resource. Take care!

**Comment by TheMightyKegel** [comment]
I apologize for any confusion - thanks for the honest feedback!
